<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '51b031972ee062421ac41127d9391fd6',
  'DATABASE_URL' => 'mysql://admin:Camfrog300@aa215639-001.privatesql:35441/symfony',
  'CORS_ALLOW_ORIGIN' => '^https?://paramall.tn:?[0-9]*$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '53223209',
  'MAILER_DSN' => 'smtp://no-reply@paramall.tn:oILiopxxxxxx78@ssl0.ovh.net:587',
);
